from .usuario import UsuarioViewSet
from .endereco import EnderecoViewSet
from .cartao import CartaoViewSet
from .forma_pagamento import Forma_PagamentoViewSet
from .itens_compra import ItensCompraViewSet
from .marca import MarcaViewSet
from .cor import CorViewSet
from .tamanho import TamanhoViewSet
from .produto import ProdutoViewSet
from .pedido import PedidoViewSet
from .avaliacao import AvaliacaoViewSet
