# Generated by Django 4.1 on 2022-09-04 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tipo_Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=120)),
                ("senha", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=14)),
                ("sexo", models.CharField(default="Indefinido", max_length=10)),
                ("contato", models.CharField(max_length=15, null=True)),
                ("nome", models.CharField(max_length=50)),
                ("sobrenome", models.CharField(max_length=100)),
                ("dt_nasc", models.DateField(default=datetime.datetime.now)),
                (
                    "id_tipousuario_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.tipo_usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=2)),
                ("municipio", models.CharField(max_length=75)),
                ("bairro", models.CharField(max_length=75)),
                ("logradouro", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("complemento", models.CharField(max_length=30)),
                ("referencia", models.CharField(max_length=255, null=True)),
                (
                    "id_usuario_FK",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.usuario"
                    ),
                ),
            ],
        ),
    ]
