# Generated by Django 4.1 on 2022-09-07 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("cpf", models.CharField(max_length=14)),
                ("sexo", models.CharField(default="Indefinido", max_length=10)),
                ("contato", models.CharField(max_length=15, null=True)),
                ("nome", models.CharField(max_length=255)),
                ("sobrenome", models.CharField(max_length=255)),
                ("dt_nasc", models.DateField(default=datetime.datetime.now)),
                ("ativo", models.BooleanField(default=True)),
                ("admin", models.BooleanField(default=False)),
                ("super_usuario", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
