# Generated by Django 4.1 on 2022-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="data_entrega",
            field=models.DateField(null=True),
        ),
    ]
