# Generated by Django 4.1 on 2022-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ped_pro_pedido_alter_ped_pro_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="itens",
        ),
        migrations.AddField(
            model_name="produto",
            name="pedidos",
            field=models.ManyToManyField(
                related_name="itens", through="core.Ped_Pro", to="core.pedido"
            ),
        ),
    ]
