# Generated by Django 4.1 on 2022-09-09 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cor_endereco_forma_pagamento_marca_ped_pro_tamanho_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data_pedido",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
