# Generated by Django 4.1 on 2022-11-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_pedido_qtd_parcela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="produto_avaliado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avaliacoes",
                to="core.produto",
            ),
        ),
    ]
