# Generated by Django 4.1 on 2022-09-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_produto_pedidos_itenscompra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.produto",
            ),
        ),
    ]
