# Generated by Django 4.1 on 2022-11-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_avaliacao_produto_avaliado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacao",
            old_name="produto_avaliado",
            new_name="produto",
        ),
    ]
