# Generated by Django 4.1 on 2022-09-12 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_itenscompra_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ped_Pro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtd_produto", models.IntegerField(default=1)),
                ("data_entrada", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="itens",
            field=models.ManyToManyField(
                related_name="pedidos", through="core.Ped_Pro", to="core.produto"
            ),
        ),
        migrations.AddField(
            model_name="ped_pro",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ped_pros",
                to="core.pedido",
            ),
        ),
        migrations.AddField(
            model_name="ped_pro",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ped_pros",
                to="core.produto",
            ),
        ),
        migrations.AlterField(
            model_name="avaliacao",
            name="produto_avaliado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avaliacoes",
                to="core.ped_pro",
            ),
        ),
        migrations.DeleteModel(
            name="ItensCompra",
        ),
    ]
