# Generated by Django 4.1 on 2022-12-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_produto_avaliado_avaliacao_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="preco_total",
        ),
    ]
